source 'http://rubygems.org'

ruby '3.4.6'

gem 'base64'
gem 'bigdecimal'
gem 'chronic'
gem 'chronic_duration'
gem 'csv'
gem 'grape'
gem 'hashie'
gem 'httparty'
gem 'irb'
gem 'mongoid'
gem 'mongoid-locker'
gem 'mongoid-scroll'
gem 'newrelic_rpm'
gem 'newrelic-slack-ruby-bot'
gem 'nokogiri'
gem 'open-weather-ruby-client'
gem 'ostruct'
gem 'polylines'
gem 'puma'
gem 'rack'
gem 'rack-robotz'
gem 'rack-server-pages'
gem 'ruby-enum'
gem 'slack-ruby-bot-server-mailchimp'
gem 'slack-ruby-bot-server-rtm'
gem 'strava-ruby-client'
gem 'stripe', '~> 1.58.0'
gem 'wannabe_bool'

group :development, :test do
  gem 'foreman'
  gem 'rake', '~> 12.3'
  gem 'rubocop'
  gem 'rubocop-capybara'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
end

group :development do
  gem 'mongoid-shell'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner-mongoid'
  gem 'fabrication'
  gem 'faker'
  gem 'faraday-rack'
  gem 'hyperclient'
  gem 'rack-test'
  gem 'rackup'
  gem 'rspec'
  gem 'selenium-webdriver'
  gem 'stripe-ruby-mock', '~> 2.4.1', require: 'stripe_mock'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
