require 'slack-strava/commands/mixins'
require 'slack-strava/commands/help'
require 'slack-strava/commands/info'
require 'slack-strava/commands/subscription'
require 'slack-strava/commands/connect'
require 'slack-strava/commands/disconnect'
require 'slack-strava/commands/set'
require 'slack-strava/commands/clubs'
